version: '3.8'
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:latest
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloakDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:latest
    command: [ "start-dev", "--import-realm" ] #start in development mode -> import realm configs in provided directory
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql #POINTS TO MYSQL DATABASE
      DB_DATABASE: keycloakDb
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

